language: c
before_install:
    - echo "deb http://fr.archive.ubuntu.com/ubuntu/ trusty universe" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
install:
    - sudo apt-get update
    - sudo apt-get install libfuse-dev librdkafka-dev
    - pip install fabricate
script: "./build.py"
